import { Injectable, computed, effect, signal } from '@angular/core';
import { FR } from './fr';

export type Lang = 'en' | 'fr';

const STORAGE_KEY = 'recoverai.lang';

function initialLang(): Lang {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === 'en' || stored === 'fr') return stored;
  } catch {
    // storage unavailable (private mode): fall through to the browser language
  }
  return navigator.language.toLowerCase().startsWith('fr') ? 'fr' : 'en';
}

// The English text is the translation key, so templates stay readable and a
// missing French entry simply falls back to English.
@Injectable({ providedIn: 'root' })
export class I18nService {
  readonly lang = signal<Lang>(initialLang());
  readonly locale = computed(() => (this.lang() === 'fr' ? 'fr-FR' : 'en-US'));

  constructor() {
    effect(() => {
      document.documentElement.lang = this.lang();
      try {
        localStorage.setItem(STORAGE_KEY, this.lang());
      } catch {
        // ignore: the choice just won't persist
      }
    });
  }

  setLang(lang: Lang) {
    this.lang.set(lang);
  }

  t(key: string, params?: Record<string, string | number>): string {
    const text = (this.lang() === 'fr' ? FR[key] : undefined) ?? key;
    if (!params) return text;
    return text.replace(/\{(\w+)\}/g, (_, name: string) => String(params[name] ?? `{${name}}`));
  }

  // Strings generated by the database (risk explanations, recommended actions).
  translateDb(text: string | null | undefined): string {
    if (!text) return '';
    if (text.includes(' · ')) {
      return text
        .split(' · ')
        .map((part) => this.translateDb(part))
        .join(' · ');
    }
    const days = /^(\d+) days without contact$/.exec(text);
    if (days) return this.t('{n} days without contact', { n: days[1] });
    const sent = /^Email sent: (.*)$/.exec(text);
    if (sent) return this.t('Email sent: {subject}', { subject: sent[1] });
    const received = /^Email received: (.*)$/.exec(text);
    if (received) return this.t('Email received: {subject}', { subject: received[1] });
    const recovered = /^Revenue recovered — (.*)$/.exec(text);
    if (recovered) return this.t('Revenue recovered — {amount}', { amount: recovered[1] });
    return this.t(text);
  }
}
